### ISSUE TITLE
Otsida 5. küsimusele vastus

### ISSUE THREAD

**Issue by terjevolke** [kuressaareametikool/devopsdemo#5]

**Comment by terjevolke** [comment]
vastus on kana, see on eraldi forkis praegu

**Comment by randoschool** [comment]
pushi üles ja tee pull request

**Comment by terjevolke** [comment]
ma ei saaaaa
<img width="263" alt="Kuvatõmmis 2021-02-19 164458" src="https://user-images.githubusercontent.com/27761344/108519006-e7587f00-72d1-11eb-8627-0808a2a9e0e3.png">

**Comment by randoschool** [comment]
Loe seda. Vaata kas siis saad.

https://docs.github.com/en/github/using-git/setting-your-username-in-git

Päikest ☀️
Rando Õispuu


On 19. Feb 2021, at 16:46, terjevolke <notifications@github.com> wrote:

﻿

ma ei saaaaa
[Kuvatõmmis 2021-02-19 164458]<https://user-images.githubusercontent.com/27761344/108519006-e7587f00-72d1-11eb-8627-0808a2a9e0e3.png>

**Comment by terjevolke** [comment]
pushed to main, waiting for acceptance
